mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    url(r'^$', TemplateView.as_view(template_name='polls/index.html'), name='home')
]

mysite/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^sign_in/$', views.sign_in, name='sign_in'),
    url(r'^login/$', views.login, name='login'),
    url(r'^user/(?P<username>[a-zA-Z0-9]+)/$', views.user_page, name='user_page'),
    url(r'^user/(?P<username>[a-zA-Z0-9]+)/(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^user/(?P<username>[a-zA-Z0-9]+)/(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^user/(?P<username>[a-zA-Z0-9]+)/(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^user/(?P<username>[a-zA-Z0-9]+)/add_question/$', views.add_question, name='add_question'),
    url(r'^user/(?P<question_id>[0-9]+)/add_choices/$', views.add_choices, name='add_choices'),
    url(r'^user/(?P<question_id>[0-9]+)/edit_question/$', views.edit_question, name='edit_question'),

]

mysite/polls/models.py
from django.db import models


class User(models.Model):
    username = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=50)

    def __str__(self):
        return self.username


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/polls/forms.py
from datetime import date, datetime

from django import forms

from .models import Choice


class LogForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'a-zA-Z0-9'}))
    password = forms.CharField(widget=forms.PasswordInput())


class AddQuestionForm(forms.Form):
    question_text = forms.CharField()
    date = forms.DateField(widget=forms.DateInput(attrs={'placeholder': 'YYYY-MM-DD'}), initial=date.today)
    time = forms.TimeField(widget=forms.TimeInput(attrs={'placeholder': 'HH:MM:SS'}), initial=datetime.now)


class AddChoiceForm(forms.Form):
    choice_text = forms.CharField()
    votes = forms.IntegerField(widget=forms.NumberInput(attrs={'min': '0'}), initial=0)

AddChoiceFormset = forms.formset_factory(AddChoiceForm, extra=3)
# AddChoiceFormset = forms.modelformset_factory(model=Choice, fields=['choice_text', 'votes'])


class EditQuestionForm(forms.Form):
    question_text = None
    choices = None

    def __init__(self, choices, question_text):
        forms.Form.__init__(self)
        self.fields["question_text"] = forms.CharField(label="New question text:", initial=question_text)
        self.fields["choices"] = forms.MultipleChoiceField(required=False, widget=forms.CheckboxSelectMultiple,
                                                           choices=choices, label="Select choices to be deleted:")

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic

from .models import User, Question, Choice
from .forms import LogForm, AddQuestionForm, AddChoiceForm, EditQuestionForm, AddChoiceFormset
from django.db import IntegrityError

from datetime import datetime


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'questions_list'

    def get_queryset(self):
        """
           Return all the questions
        """
        return Question.objects.all()


def sign_in(request):
    if request.method == 'POST':
        form = LogForm(request.POST)
        if form.is_valid():
            try:
                user = User(username=form.cleaned_data["username"],
                            password=form.cleaned_data["password"])
                user.save()
                return redirect('polls:user_page', username=user.username)
            except IntegrityError:
                form = LogForm()
                return render(request, "polls/sign_in.html", {
                    "error_msg": "Username already exists",
                    "form": form
                    })

    form = LogForm()
    return render(request, "polls/sign_in.html", {"form": form})


def login(request):
    if request.method == 'POST':
        form = LogForm(request.POST)
        if form.is_valid():
            try:
                user = User.objects.get(username=form.cleaned_data["username"],
                                        password=form.cleaned_data["password"])
                return redirect('polls:user_page', username=user.username)
            except User.DoesNotExist:
                form = LogForm()
                return render(request, "polls/login.html", {
                    "error_msg": "Username or password incorrect",
                    "form": form})

    form = LogForm()
    return render(request, "polls/login.html", {"form": form})


def user_page(request, username):
    user = get_object_or_404(User, username=username)
    questions = Question.objects.filter(user=user)

    return render(request, "polls/user_page.html", {"user": user, "questions": questions})


def detail(request, username, question_id):
    question = get_object_or_404(Question, pk=question_id)
    user = get_object_or_404(User, username=username)

    return render(request, 'polls/detail.html', {"user": user, 'question': question})


def results(request, username, question_id):
    question = get_object_or_404(Question, pk=question_id)
    user = get_object_or_404(User, username=username)

    return render(request, 'polls/results.html', {"user": user, 'question': question})


def vote(request, username, question_id):
    user = get_object_or_404(User, username=username)
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'user': user,
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return redirect('polls:results', username=user.username, question_id=question.id)


def add_question(request, username):
    user = get_object_or_404(User, username=username)
    if request.method == 'POST':
        form = AddQuestionForm(request.POST)
        if form.is_valid():
            date = form.cleaned_data["date"]
            time = form.cleaned_data["time"]
            pub_date = datetime.combine(date, time)
            question = Question(question_text=form.cleaned_data["question_text"],
                                pub_date=pub_date,
                                user=user)
            question.save()
            return redirect('polls:user_page', username=user.username)
        else:
            form = AddQuestionForm()
            return render(request, "polls/add_question.html", {
                "user": user,
                'error_message': "Invalid input",
                'form': form,
            })

    form = AddQuestionForm()
    return render(request, "polls/add_question.html", {"user": user, "form": form})


def add_choices(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        formset = AddChoiceFormset(request.POST)
        if formset.is_valid():
            for form in formset:
                if form.cleaned_data:
                    choice = Choice(choice_text=form.cleaned_data["choice_text"],
                                    votes=form.cleaned_data["votes"],
                                    question=question)
                    choice.save()
            user = question.user
            return redirect('polls:detail', username=user.username, question_id=question_id)

    formset = AddChoiceFormset()
    return render(request, "polls/add_choice.html", {"question": question, "formset": formset})


def edit_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        Question.objects.filter(pk=question_id).update(question_text=request.POST["question_text"])
        choices_to_delete_ids = request.POST.getlist("choices")
        for choice_id in choices_to_delete_ids:
            choice = get_object_or_404(Choice, pk=choice_id)
            choice.delete()
        return redirect('polls:detail', username=question.user.username, question_id=question_id)

    choices = set()
    for choice in question.choice_set.all():
        choices.add((choice.id, choice.choice_text))
    form = EditQuestionForm(choices=choices, question_text=question.question_text)
    return render(request, "polls/edit_question.html", {"question": question, "form": form})

mysite/polls/templates/polls/add_choice.html
{% if error_message %}<p>{{error_message}}</p>{% endif %}

<form action="{% url 'polls:add_choices' question.id%}" method="post">
{% csrf_token %}
    {{formset.as_p}}
    <input type="submit" value="Save" />
</form>

<a href="{% url 'polls:user_page' question.user.username %}">Home</a>

mysite/polls/templates/polls/add_question.html
{% if error_message %}<p>{{error_message}}</p>{% endif %}

<form action="{% url 'polls:add_question' user.username%}" method="post">
{% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save" />
</form>

<a href="{% url 'polls:user_page' user.username %}">Home</a>

mysite/polls/templates/polls/detail.html
<h1>{{user.username}}: {{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% if question.choice_set.count %}
<form action="{% url 'polls:vote' user.username question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
    <br>
<input type="submit" value="Vote" />
</form>
{% endif %}

<form action="{% url 'polls:edit_question' question.id %}">
<input type="submit" value="Edit question" />
</form>

<form action="{% url 'polls:add_choices' question.id %}">
<input type="submit" value="Add choices" />
</form>

<a href="{% url 'polls:user_page' user.username %}">Home</a>

mysite/polls/templates/polls/edit_question.html
{% if error_message %}<h1>{{error_message}}</h1>{% endif %}

<form action="{% url 'polls:edit_question' question.id%}" method="post">
{% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save" />
</form>

<a href="{% url 'polls:user_page' question.user.username %}">Home</a>

mysite/polls/templates/polls/index.html
{% if questions_list %}
    <ul type="none">
    {% for question in questions_list %}
        <li>{{ question.question_text }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
<ul type="none">
    <li><a href="{% url 'polls:sign_in'%}">Sign In</a></li>
    <li><a href="{% url 'polls:login'%}">Login</a></li>
</ul>

mysite/polls/templates/polls/login.html
{% if error_msg %}<h1>{{error_msg}}</h1>{% endif %}

<form action="{% url 'polls:login' %}" method="post">
{% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Login" />
</form>

<a href="{% url 'polls:index'%}">Home</a>

mysite/polls/templates/polls/results.html
<h1>{{user.username}}: {{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' user.username question.id %}">Vote again?</a> <br>
<a href="{% url 'polls:user_page' user.username %}">Home</a>

mysite/polls/templates/polls/sign_in.html
{% if error_msg %}<h1>{{error_msg}}</h1>{% endif %}

<form action="{% url 'polls:sign_in' %}" method="post">
{% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Sign In" />
</form>

<a href="{% url 'polls:index'%}">Home</a>

mysite/polls/templates/polls/user_page.html
{% if questions %}
    <ul type="none">
    {% for question in questions %}
        <li><a href="{% url 'polls:detail' user.username question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}


<form action="{% url 'polls:add_question' user.username %}">
<input type="submit" value="Add question" />
</form>

<a href="{% url 'polls:index'%}">Log Out</a>